import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "@/styles/globals.css";

import { AppProvider } from "@/providers/app";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppinsFont = Poppins({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  fallback: ["Helvetica", "Arial", "sans-serif"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppinsFont.className} dark`}
    >
      <body>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
